name: "Solution1"
on: workflow_dispatch
permissions:
  contents: write
  actions: write
jobs:
  job1:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v5 
        with:
          python-version: '3.10'
      - name: "generate solution"
        run: |
          python3 -m pip install diagrams,graphviz
          python Solution1.py
