name: "Solution1"
on: workflow_dispatch
permissions:
  contents: write
  actions: write
jobs:
  job1:
    runs-on: "ubuntu-latest"
    steps:
      - name: "generate solution"
        run: |
          python Solution1.py
